### ISSUE TITLE
Precipitation Data

### ISSUE THREAD

**Issue by bekaxe** [c5te1n/node-red-contrib-dwd-local-weather#1]
Hi, 
I think this is a great project utilizing high quality data from DWD. 
I would be really interested in also getting the precipitation, as I am living near an airport. 

Would you consider opening up the node for current/historic data? 

This would be great to use for automation of garden irrigation.

**Comment by c5te1n** [comment]
Hi,
thank you, glad you find it useful!
You should be able to get precipitation data by adding it as an "additional field" in the configuration to the node. So to get the probability for a precipitation of more than 0.1mm just use R101. See this doc for available fields:
https://www.dwd.de/DE/leistungen/opendata/help/schluessel_datenformate/kml/mosmix_elemente_pdf.pdf

As for current weather data:
I would like to add this. Challenge here is that the current data feed (MOSMIX L) is updated a few times a day. A more frequently (hourly) updated feed is available from DWD (MOSMIX S), but requires a ~40MB download every hour. I am looking into options to avoid this.

As for historic weather, tyou can save the output of the node into an influx DB and then query that.

**Comment by c5te1n** [comment]
Further to the above, the latest version (0.1.4) now also includes a field `precipitation%` for easier use.
