### ISSUE TITLE
lookahead hours explanation

### ISSUE THREAD

**Issue by ctr49** [c5te1n/node-red-contrib-dwd-local-weather#16]
I don't see a difference in the output between lookahead hours 0, 24 or 72. What is the expected result of setting lookahead hours?

**Comment by c5te1n** [comment]
When you set lookahead hours, the weather data returned will be for x hours in the future. If you look at the temperature for 12 hours ahead for example, you should see a different number returned unless that temperature happens to be exactly the same.
