### ISSUE TITLE
MOSMIX Station

### ISSUE THREAD

**Issue by dmenne** [c5te1n/node-red-contrib-dwd-local-weather#2]
MOSMIX station number field "id" is requested, but this field contains alphabetic character, e.g. "EW020", which is reported as a error.

**Comment by dmenne** [comment]
Partially corrected: When ids such as Q554 are entered, retrieval works, but the icon gives a warning on save and the red triangle.

**Comment by c5te1n** [comment]
Thanks for reporting! I will fix this in the next release.

**Comment by c5te1n** [comment]
This is fixed now in 0.1.5.
