### ISSUE TITLE
Add msg.topic for easier stream handling

### ISSUE THREAD

**Issue by dimw** [c5te1n/node-red-contrib-dwd-local-weather#23]
It [seems to be a good practice](https://nodered.org/docs/developing-flows/message-design#using-msgtopic) to set the `msg.topic` when generating a message. A message topic is handy esp. when merging data from different streams (e.g. in a subsequent `join` node).

**Acceptance Criteria**
1. The workflow designer is able to set a message topic for the `dwdweather` node via the node editing window.
2. The generated messages contain the previously set topic in the `msg.topic` property.

**Comment by c5te1n** [comment]
Added in 1.0.0. Thanks for your contribution.
