### ISSUE TITLE
linked "additional fields"-pdf isn't available anymore | found similar file

### ISSUE THREAD

**Issue by ElektrikTrick** [c5te1n/node-red-contrib-dwd-local-weather#28]
File isn't available anymore, link refers to a 404-page, probably the dwd deleted the file.

I found a "similar" pdf from dwd: https://www.dwd.de/DE/leistungen/met_verfahren_mosmix/mosmix_parameteruebersicht.pdf?__blob=publicationFile&v=4

**Comment by c5te1n** [comment]
Thanks for your note and providing the link. I have updated this and it will go live with the next release.
