### ISSUE TITLE
Additional fields not working?

### ISSUE THREAD

**Issue by P1Rebo** [c5te1n/node-red-contrib-dwd-local-weather#3]
First of all, thanks for providing this library!

Just tried out your node using Station ID 10655 (Würzburg). As I try to read out several additional fields it doesn't work. E.g. "RR1c" or "DRR1". Tried with and without quotation marks and using just one field id.

It returns "MOSMIX attribute "RR1c" not known or not processed" as node.warning.

Thanks for any hints!

**Comment by gungam** [comment]
Experiencing no problems with the same station id an although the same attributes.
![Bildschirmfoto 2019-05-16 um 22 11 34](https://user-images.githubusercontent.com/6289350/57885879-413e3200-782c-11e9-93ba-e224118e5ca6.png)
![Bildschirmfoto 2019-05-16 um 22 06 53](https://user-images.githubusercontent.com/6289350/57885880-413e3200-782c-11e9-9031-74cb3caadc68.png)

**Comment by P1Rebo** [comment]
Ok, indeed it worked out now. I really don't know why... So I'll close this issue again. Thanks!
