### ISSUE TITLE
Node triggers chain on deployment

### ISSUE THREAD

**Issue by janbro1** [c5te1n/node-red-contrib-dwd-local-weather#35]
Every time a flow is deployed the DWD node triggers the chain. An option to prevent it from doing so does not exist.
The intended method in this use case would have been to take action upon triggered.

**Comment by c5te1n** [comment]
Hi, please use the "Omit message on start" option that has been added in one of the more recent versions. See readme.

**Comment by janbro1** [comment]
> 
> 
> Hi, please use the "Omit message on start" option that has been added in one of the more recent versions. See readme.

Apologies, but this option does not appear to be available. I run node red 2.6. on docker and verified that I have the latest available version for installation of your node. The version of your node I have is 1.0.1.. I was unable to verify whether this is an even later version available.
In the mentioned readme I have found the paragraph, but I don't see the option in the screenshot (and I assume it would be a checkbox to select). Secondly the documentation available through the node red website does not list this option either (https://flows.nodered.org/node/node-red-contrib-dwd-local-weather).
Could you please verifiy that this option is available in the available node red addons? It does appear as if this was made available in a beta version but is not yet realeased to the public.
