### ISSUE TITLE
Dead Link to mosmix elements list in the readme

### ISSUE THREAD

**Issue by nakla** [c5te1n/node-red-contrib-dwd-local-weather#38]
New Link possibly [https://www.dwd.de/DE/leistungen/met_verfahren_mosmix/mosmix_parameteruebersicht.html](https://www.dwd.de/DE/leistungen/met_verfahren_mosmix/mosmix_parameteruebersicht.html)
I don't know, if there is another list, because I am missing the parameter SunD in that list, which i wanted to use...

**Comment by NaincyKumariKnoldus** [comment]
Hey @nakla I would love to do this. 
I have fixed this link in readme file. I have raised a PR for this. 
Please review my PR.
Thanks!

**Comment by nakla** [comment]
Link works. Thanks for fixing so fast.

**Comment by NaincyKumariKnoldus** [comment]
Hey @nakla but you have not merged my PR yet. Please Have a look.
