### ISSUE TITLE
Crashes on boot when connection could not be established.

### ISSUE THREAD

**Issue by WhiteLionATX** [c5te1n/node-red-contrib-dwd-local-weather#44]
In my case my internet connection was lost for a while and whole node red crashed:

`7 Sep 20:02:12 - [red] Uncaught Exception:
7 Sep 20:02:12 - [error] ReferenceError: response is not defined
    at /home/pi/.node-red/node_modules/node-red-contrib-dwd-local-weather/dwdweather.js:92:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by c5te1n** [comment]
This is fixed in the latest version based on the patch you provided. Thanks for contributing!
