### ISSUE TITLE
Update flows.nodered.org

### ISSUE THREAD

**Issue by winnieXY** [c5te1n/node-red-contrib-dwd-local-weather#47]
Hey,

if you try to install your plugin via the front end palette you still get 1.0.2 which is already superseeded. See: https://flows.nodered.org/node/node-red-contrib-dwd-local-weather

Please upload the newest version also th nodered.org

With best regards
Patrick

**Comment by c5te1n** [comment]
Thanks for your note - this has been fixed now.
