### ISSUE TITLE
For the field "ww" some strange decimal numbers are returned

### ISSUE THREAD

**Issue by biker8491** [c5te1n/node-red-contrib-dwd-local-weather#48]
The "ww" filed is defined as integer but I get for some hourly forecasts strange decimal numbers. This happens only for those hours where the value is changing compared to the previous hour.
[ww.pdf](https://github.com/c5te1n/node-red-contrib-dwd-local-weather/files/10107500/ww.pdf)

**Comment by c5te1n** [comment]
The node is doing interpolation to return the best value for the time given. So if the data gives a value of 10 for 10:00 and 20 for 11:00 and you are requesting the value for 10:30 it will calculate the return value to be 15. You can use the `<` and `>` output modifiers to return 10 or 20 in those cases.

**Comment by biker8491** [comment]
In the case of the „ww“-values interpolation does not make any sense because this value is defined for intergers only. For example, the value of 75 is defined as “heavy snowfall, continuous” and the next valid value is 80 which is defined as “slight rain shower”. An interpolated between these values cannot be used. Also rounding does not help because you get not defined values. The result of interpolation is that you are missing for one or two hours value information.
All of the following parameters are defined the same: WPc11, WPc31, WPc61, WPcd1, WPch1, ww and ww3. The parameter W1W2 is also defined as integer code, but have different meanings. To be usefull all of these parameters should not be interpolated.
See here: https://www.dwd.de/DE/leistungen/opendata/help/schluessel_datenformate/kml/mosmix_elemente_xls.xlsx?__blob=publicationFile&v=7
