### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by markusleben** [c5te1n/node-red-contrib-dwd-local-weather#8]
I just tried out your dwd skill and run into this error when monitoring the output over the debug node:

`TypeError: updateWeatherForecastIfOutdated(...).then(...).catch(...).finally is not a function`

Is this a known issue?

**Comment by c5te1n** [comment]
I have not seen this before, but from having a quick look, this might happen if you are using a nodejs version <10.0.0. Are you?

**Comment by markusleben** [comment]
Indeed. It is v8.12.0. I used it with the ioBroker Version of NodeRed. Is it possible to make it backward compatible?

**Comment by Bundeshorst** [comment]
same problem here. Any chance to run it with nodejs 8.12.0?

**Comment by c5te1n** [comment]
The latest version of ioBroker seems to come bundled with nodeJS 10. Is it an option to upgrade to this instead?
See: https://www.iobroker.net/#de/download

**Comment by renne** [comment]
Same situation here. I don't know which version of `node.js` is used by ct-Smarthome, but `node-red-contrib-dwd-local-weather` publishes once on start-up and shows `Requesting latest MOSMIX data file` forever. Triggering an inject node manually doesn't help.

**Comment by merlinschumacher** [comment]
The next update will be moved to NodeJS 12 (and maybe there will be a variant for 10) since Node-Red now offers an official docker image. This image will just add a few nodes to the official image.

**Comment by c5te1n** [comment]
Closing this as the Docker container `ct-Smart-Home` is based on `nodered/node-red:latest-minimal`, which is on node 10 right now.
