### ISSUE TITLE
how to use precipitation%

### ISSUE THREAD

**Issue by dueni0** [c5te1n/node-red-contrib-dwd-local-weather#9]
I can use all fields except precipitation%. It seems that the percent sign in msg.payload.precipitation% is the problem, is there a way to escape it?

**Comment by c5te1n** [comment]
It should work without escaping it, but depends on what you are doing in subsequent nodes and how they are programmed. To avoid issues, you can pass the result of this node to a change node to set an additional 'precipitation_perc' field to the value of 'precipitation%'.

**Comment by c5te1n** [comment]
The name has been changed to 'precipitation_perc' in v0.1.8 to make this easier to use. 'precipitation%' stays available for backward compatibility.
